language: node_js
node_js:
  - "0.10"

addons:
  sauce_connect: true

before_install:
  - "npm install protractor selenium-server-standalone-jar --save"

notifications:
  email:
   - brian@qualityshepherd.com
